# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "books", :force => true do |t|
    t.column "title", :string
    t.column "isbn", :string
    t.column "comment", :text
    t.column "tags", :string
  end

  add_index "books", ["isbn"], :name => "books_isbn_index"

  create_table "documents", :force => true do |t|
    t.column "book_id", :integer
    t.column "path", :string
    t.column "format", :string
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "users", :force => true do |t|
    t.column "name", :string
    t.column "hashed_password", :string
    t.column "salt", :string
  end

end
